In [1]:
import numpy as np

In [2]:
#Q.No_1>  Create a NumPy array 'arr' of integers from 0 to 5 and print its data type. 
arr=np.array(range(0,5+1))

for i in range(0,5+1):
    print(type(arr[i]))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [3]:
#Q_No_2> Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr=np.array([1.5,2.6,3.7])
count=0
n=len(arr)
for i in range(0,n):
    if type(arr[i])==np.float64:
        count+=1
if count==len(arr):
    print("data types is float64")

data types is float64


In [4]:
#Q_No_3>  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
l=[1,2,3]
arr=np.array(l,dtype='complex128')
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

In [5]:
#Q_No_4> Convert an existing NumPy array 'arr' of integers to float32 data type.
arr=np.array([1,2,3,4])
arr_flaot32=arr.astype(np.float32)
print("Data type of original arr",arr.dtype)
print("Data type of nverted arr",arr_flaot32.dtype)

Data type of original arr int32
Data type of nverted arr float32


In [6]:
#Q_No_5> . Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.123456789, 2.987654321, 3.1415926535], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print("Original arr",arr)
print("Data type of original arr",arr.dtype)
print("Converted arr",arr_flaot32)
print("Data type of nverted arr",arr_flaot32.dtype)

Original arr [1.12345679 2.98765432 3.14159265]
Data type of original arr float64
Converted arr [1. 2. 3. 4.]
Data type of nverted arr float32


In [7]:
#Q_No_6> Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_atrriibutes(n):
    arr=np.array([i for i in range(0,n)])
    print(arr)
    print(arr.shape)
    print(arr.size)
    print(arr.dtype)

array_atrriibutes(5)

[0 1 2 3 4]
(5,)
5
int32


In [8]:
#Q_No_7>  Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(n):
    arr=np.array([i for i in range(0,n)])
    return arr.ndim

n=int(input("enter size of array"))
print(array_dimension(5))

In [ ]:
#Q_No_8> Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(n):
    arr=np.array([i for i in range(0,n)])
    return arr.size,arr.byteswap()

n=int(input("enter size of array"))
print(item_size_info(n))

In [ ]:
#Q_No_9>  9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(n):
    arr=np.array([i for i in range(0,n)])
    return arr.strides

n=int(input("enter size of array"))
print(array_strides(n))

In [ ]:
#Q_No_10>  Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(n):
    arr=np.array([i for i in range(0,n)])
    return arr.shape,arr.strides

n=int(input("enter size of array"))
print(shape_stride_relationship(n))


In [1]:
#Q_No_11>. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` element
def create_zeros_array(n):
    arr=np.zeros((n))
    return arr

n=int(input("enter size of array"))
print(create_zeros_array(n))

In [2]:
#Q_No_12>Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_array(n,m):
    arr=np.zeros((n,m))
    return arr

n=int(input("enter row of array"))
m=int(input("enter column of array"))

print(create_ones_array(n,m))

In [ ]:
#Q_No_13> Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step`.

def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

array=generate_range_array(1,10,2)
print(array)


[1 3 5 7 9]


In [ ]:
#Q_No_14> Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start,stop,num):
    return np.arange(start,stop,num)

array=generate_linear_space(0.0,1.0,5)
print(array)

[0.]


In [ ]:
#Q_No_15>  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    arr=np.eye((n))
    return arr

n=int(input("enter no of  array"))

print(create_identity_matrix(n))

In [ ]:
#Q_No_16> Write a function that takes a Python list and converts it into a NumPy array.
def convert_arr(list):
    return np.array(list)

array=convert_arr([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [1]:
#Q_No_17> Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr1=np.ones((3,4))
arr2=np.ones((4,3))
def func(arr1,arr2):
    print(np.concatenate(arr1,arr2))

func(arr1,arr2)

NameError: name 'np' is not defined

In [ ]:
#Q_No_18> Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def conc_arr(arr1,arr2,axis):
    return np.concatenate((arr1,arr2),axis=axis)

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
conc_arr(arr1,arr2,0)


array([1, 2, 3, 4, 5, 6])

In [ ]:
#Q_No_19> Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
def conc_arr(arr1,arr2):
    return np.concatenate((arr1,arr2),axis=1)

arr1=np.array([[1,2,3],[2,3,5]])
arr2=np.array([[4],[3]])
conc_arr(arr1,arr2)

array([[1, 2, 3, 4],
       [2, 3, 5, 3]])

In [ ]:
#Q_No_20>  Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(array):
    return np.vstack(array)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
array3 = np.array([[7, 8], [9, 10]])

result = vertical_stack([array1, array2, array3])
print(result)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#Q_No_21>  Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def create_arr(start,stop,step):
    return np.arange(start,stop,step)
array = create_arr(1, 10, 2)
print(array)


[1 3 5 7 9]


In [ ]:
#Q_No_22> . Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def gen_equally_spaced():
    array=np.linspace(0,1,10)
    return array

print(gen_equally_spaced())

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#Q_No_23> Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def log_arr():
    return np.logspace(1,1000,5)

print(log_arr())

[1.00000000e+001 5.62341325e+250             inf             inf
             inf]


In [ ]:
#Q_No_24> . Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd
pd.DataFrame(np.random.randint(1,100,size=(5,3)))

   A   B
0  1  10
1  0  20
2  3 -30
3  0  40
4  5 -50


In [ ]:
#Q_No_25>  Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
def replace_negatives_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {'A': [1, -2, 3, -4, 5], 'B': [10, 20, -30, 40, -50]}
df = pd.DataFrame(data)

# Replacing negative values in column 'A'
modified_df = replace_negatives_with_zero(df, 'A')
print(modified_df)

   A   B
0  1  10
1  0  20
2  3 -30
3  0  40
4  5 -50


In [2]:
#Q_No_26>Access the 3rd element from the given NumPy array.
arr=np.array([10,20,30,40,50])
print(arr[2])

In [3]:
#Q_No_27> Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[1][2])


In [4]:
#Q_No_28>Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.extract(arr>5))

In [5]:
#Q_No_29>. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:5])

In [6]:
#Q_No_30>Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[0:2,1:3])

In [ ]:
#Q_No_31> Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements(array_2d, indices):
    rows, cols = indices[:, 0], indices[:, 1]
    extracted_elements = array_2d[rows, cols]
    return extracted_elements

array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

indices = np.array([[0, 1],  # Element at (0, 1) -> 20
                    [1, 2],  # Element at (1, 2) -> 60
                    [2, 0]]) # Element at (2, 0) -> 70

# Extracting elements
extracted_elements = extract_elements(array_2d, indices)
print(extracted_elements) 

In [ ]:
#Q_NO_32>Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter_greater_than(array, threshold):
    mask = array > threshold
    
    # Use the boolean mask to filter the elements
    filtered_array = array[mask]
    
    return filtered_array

# Creating a sample 1D array
array = np.array([1, 5, 7, 2, 9, 4])

# Setting a threshold value
threshold = 4

# Filtering elements greater than the threshold
filtered_elements = filter_greater_than(array, threshold)
print(filtered_elements) 

In [ ]:
#Q_NO_33>Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_3d_elements(array_3d, row_indices, col_indices, depth_indices):
    # Use the indices to extract the elements
    extracted_elements = array_3d[row_indices, col_indices, depth_indices]
    
    return extracted_elements


# Creating a sample 3D array
array_3d = np.array([[[10, 20, 30],
                      [40, 50, 60],
                      [70, 80, 90]],
                     [[11, 21, 31],
                      [41, 51, 61],
                      [71, 81, 91]],
                     [[12, 22, 32],
                      [42, 52, 62],
                      [72, 82, 92]]])

# Defining indices for each dimension
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
depth_indices = np.array([2, 1, 0])

# Extracting elements
extracted_elements = extract_3d_elements(array_3d, row_indices, col_indices, depth_indices)
print(extracted_elements)  # Output: [30 61 72]

In [ ]:
#Q_NO_34> Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def filter_elements(array, condition1, condition2):
    # Ensure conditions are boolean arrays and have the same shape as array
    if not (array.shape == condition1.shape == condition2.shape):
        raise ValueError("Array and conditions must have the same shape.")
    
    # Combine both conditions
    combined_condition = condition1 & condition2
    
    # Use the combined condition to filter the elements
    filtered_elements = array[combined_condition]
    
    return filtered_elements

array = np.array([1, 5, 7, 2, 9, 4])

# Defining conditions
condition1 = array > 3        
condition2 = array % 2 == 0     

# Filtering elements where both conditions are satisfied
filtered_elements = filter_elements(array, condition1, condition2)
print(filtered_elements)  


In [ ]:
#Q_NO_35>Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_elements_2d(array_2d, row_indices, col_indices):
    # Extract elements using row and column indices
    extracted_elements = array_2d[row_indices, col_indices]
    
    return extracted_elements

# Creating a sample 2D array
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

# Defining row and column indices
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

# Extracting elements
extracted_elements = extract_elements_2d(array_2d, row_indices, col_indices)
print(extracted_elements)  


In [ ]:
#Q_NO_36> Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr=np.random.randint(1,5,(3,3))
print(arr)
print(arr+5)

In [ ]:
#Q_NO_37>Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
def multiply_rows_by_elements(arr1, arr2):
    result = arr2 * arr1.T
    return result


arr1 = np.array([[2, 4, 6]])  
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  


result = multiply_rows_by_elements(arr1, arr2)
print(result)

[[ 2  4  6  8]
 [20 24 28 32]
 [54 60 66 72]]


In [ ]:
#Q_NO_38>Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

def add_rows_with_broadcasting(arr1, arr2):
    arr2_transposed = arr2.T
    result = arr2_transposed + arr1
    result = result.T
    return result

arr1 = np.array([[1, 2, 3, 4]])  
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]]) 
result = add_rows_with_broadcasting(arr1, arr2)
print(result)

[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [ ]:
#Q_NO_39> Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
import numpy as np

def add_arrays_broadcasting(arr1, arr2):
    result = arr1 + arr2
    return result

arr1 = np.array([[1], [2], [3]]) 
arr2 = np.array([[10, 20, 30]])   

# Adding the arrays using broadcasting
result = add_arrays_broadcasting(arr1, arr2)
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
#Q_NO_40> Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
def multiply_with_broadcasting(arr1, arr2):
    # Expand dimensions of arr2 to make the shapes compatible
    arr2_expanded = arr2[:, :, np.newaxis]  # Changing arr2 shape from (2, 2) to (2, 2, 1)
    
    # Using broadcasting to multiply arr1 with arr2_expanded
    result = arr1 * arr2_expanded
    
    return result

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]]) 

arr2 = np.array([[10, 20],
                 [30, 40]])  

# Multiplying the arrays using broadcasting
result = multiply_with_broadcasting(arr1, arr2)
print(result)


[[[ 10  20  30]
  [ 80 100 120]]

 [[ 30  60  90]
  [160 200 240]]]


In [ ]:
#Q_No_41>  Calculate column-wise mean for the given array:
arr=np.array([[1,2,3],[4,5,6]])

print(np.mean(arr,axis=0))

In [ ]:
#Q_No_42> Find maximum value in each row of the given array:
arr=np.array([[1,2,3],[4,5,6]])

print(np.max(arr,axis=1))


In [ ]:
#Q_No_43>  For the given array, find indices of maximum value in each column.
arr=np.array([[1,2,3],[4,5,6]])

print(np.MAY_SHARE_EXACT(arr,axis=0))

In [ ]:
#Q_No_44> For the given array, apply custom function to calculate moving sum along rows.
arr=np.array([[1,2,3],[4,5,6]])

print(np.cumsum(arr,axis=1))

In [ ]:
#Q_No_45> In the given array, check if all elements in each column are even.
arr=np.array([[1,2,3],[4,5,6]])

print(np.sum(arr%2==0,axis=0))

In [ ]:
#Q_No_46> Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array=np.array([1,2,3,4,5,6])
reshape_arr=original_array.reshape(2,3)

print(reshape_arr)

In [ ]:
#Q_No_47>  Create a function that takes a matrix as input and returns the flattened array.
input_matrix=np.array([[1,2,3],[4,5,6]])

def func(arr):
    return arr.flatten()

print(func(input_matrix))

In [ ]:
#Q_No_48> Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
def conc_arr(arr1,arr2,axis):
    return np.concatenate((arr1,arr2),axis=axis)

conc_arr(array1,array2,1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#Q_No_49> Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(array, indices, axis):
    sub_arrays = np.split(array, indices, axis=axis)
    return sub_arrays
sub_arrays_col = split_array(array, [1], axis=1)
print(sub_arrays_col)




IndexError: tuple index out of range

In [ ]:
#Q_No_50>  Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert values at specified indices
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)
    
    # Adjust indices to delete after insertion
    adjusted_indices_to_delete = sorted(indices_to_delete)
    
    # Delete elements at specified indices
    modified_array = np.delete(modified_array, adjusted_indices_to_delete)
    
    return modified_array

result = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result)


[ 1 10  4 11  5]


In [ ]:
#Q_No_51>  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

print(arr1+arr2)

In [ ]:
#Q_No_52> Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

print(arr2-arr1)

In [ ]:
#Q_No_53> Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
arr1=np.random.randint(1,5,(3,3))
arr2=np.random.randint(1,5,(3,3))

print(arr1*arr2)

In [ ]:
#Q_No_54>  Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

# Generate the arrays
arr1 = np.arange(2, 11, 2)  # Even integers from 2 to 10
arr2 = np.arange(1, 6)      # Integers from 1 to 5

# Perform element-wise division
result = arr1 / arr2

# Display the arrays and the result
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise division result:", result)

Array 1: [ 2  4  6  8 10]
Array 2: [1 2 3 4 5]
Element-wise division result: [2. 2. 2. 2. 2.]


In [ ]:
#Q_No_55>. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1=np.random.randint(1,5,(3,3))
arr2=np.random.randint(1,5,(3,3))

print(arr1**arr2)

In [ ]:
#Q_No_56>. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
for i in arr:
    count=0
    for j in (len(arr)):
        if arr[i]==arr[j]:
            count=count+1
    if count==0:
        print(i)        


TypeError: 'int' object is not iterable

In [ ]:
#Q_No_57>Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extrac_uppercase(array):
    return np.char.upper(array)
    
print(extrac_uppercase(arr))    


['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [ ]:
#Q_No_58> Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
#Q_No_59> Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_arrays(arr1, arr2):
    
    concatenated_array = np.char.add(arr1, arr2)
    return concatenated_array

result = concatenate_arrays(arr1, arr2)
print(result)

['HelloOpen' 'WorldAI']


In [ ]:
#Q_No_60> Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_str(arr):
    longest_num=0
    for i in range(0,len(arr)):
        if len(arr[i])>longest_num:
            longest_num=len(arr)
            str=arr[i]

    return str

print(longest_str(arr))        
    
                



pineapple


In [ ]:
#Q_No_61>Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
arr=np.random.randint(1,1000,size=(1,100))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))

471.93
483.0
81042.74510000001
284.68007499647746


In [ ]:
#Q_No_62> Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
arr=np.random.randint(1,100,size=(1,50))
print(np.percentile(arr,[25]))
print(np.percentile(arr,[75]))


[33.]
[77.]


In [ ]:
#Q_No_63>. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
arr1=np.random.randint(1,100,size=(1,50))
arr2=np.random.randint(1,200,size=(1,50))
np.corrcoef(arr1,arr2)



array([[ 1.        , -0.14502496],
       [-0.14502496,  1.        ]])

In [ ]:
#Q_No_64> Create two matrices and perform matrix multiplication using NumPy's `dot` function.
arr1=np.random.randint(1,10,size=(3,3))
arr2=np.random.randint(1,20,size=(3,2))
np.dot(arr1,arr2)


3

In [ ]:
#Q_No_65>. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
arr = np.random.randint(10, 1001, 50)
print(np.percentile(arr,10))
print(np.percentile(arr,50))
print(np.percentile(arr,90))
print(np.percentile(arr,25))
print(np.percentile(arr,75))

60.30000000000001
312.0
810.0
170.75
675.5


In [ ]:
#Q_No_66>Create a NumPy array of integers and find the index of a specific element.
arr=np.array([1,2,3,4,5,5,4,1,2])
for i in range(0,len(arr)-1):
    count=0
    for j in range(0,len(arr)):
        if arr[i]==arr[j]:
            count+=1

    if count==1:
        print(i)
        break        


     




2


In [ ]:
#Q_No_67>Generate a random NumPy array and sort it in ascending order.
arr=np.random.randint(1,100,size=(1,10))
np.sort(arr)



array([[ 2,  8, 16, 37, 46, 47, 55, 55, 85, 99]])

In [ ]:
#Q_No_68>Filter elements >20  in the given NumPy array.
arr=np.array([12,25,6,42,8,30])

print(arr[arr>20])

In [ ]:
#Q_No_69> Filter elements which are divisible by 3 from a given NumPy array.
arr=np.array([1,5,8,12,15])
print(arr[arr%3==0])

In [ ]:
#Q_No_70> For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr=np.array([10,20,30,40,50])

print(np.extract(arr>=20 and arr<=40,arr))

In [ ]:
#Q_No_ 71> For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])

print(arr.dtype==arr.dtype.byteorder)
        


False


In [ ]:
#Q_NO_72> . For the given NumPy array, perform byte swapping in place using `byteswap()
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)

print(arr)

[16777216 33554432 50331648]


In [ ]:
#Q_No_73> For the given NumPy array, swap its byte order without modifying the original array using newbyteorder()
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr=arr.newbyteorder()
print("Orignal Rray",arr)
print("Array with swapped byteorder",swapped_arr)


Orignal Rray [1 2 3]
Array with swapped byteorder [16777216 33554432 50331648]


In [ ]:
#Q_No_74> For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().
arr = np.array([1, 2, 3], dtype=np.int32)
import sys

# Example array
arr = np.array([1, 256, 65536], dtype=np.int32)

# Check system endianness
system_endianness = sys.byteorder

# Conditionally swap byte order
if system_endianness == 'little':
    swapped_arr = arr.newbyteorder('>')
elif system_endianness == 'big':
    swapped_arr = arr.newbyteorder('<')
else:
    swapped_arr = arr  
    
print("System endianness:", system_endianness)
print("Original array:", arr)
print("Conditionally swapped array:", swapped_arr)


System endianness: little
Original array: [    1   256 65536]
Conditionally swapped array: [16777216    65536      256]


In [ ]:
#Q_No_75>  For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder.
arr = np.array([1, 2, 3], dtype=np.int32)
import sys

# Example array
arr = np.array([1, 256, 65536], dtype=np.int32)

# Check system endianness
system_endianness = sys.byteorder

# Check the array's byte order
array_byte_order = arr.dtype.byteorder

# Determine if byte swapping is necessary
# `=` indicates native byte order, so no swap is needed
if array_byte_order == '=':
    print("Array is already in the native byte order; no swapping needed.")
# `<` means little-endian, `>` means big-endian
elif (array_byte_order == '<' and system_endianness == 'big') or (array_byte_order == '>' and system_endianness == 'little'):
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")


Array is already in the native byte order; no swapping needed.


In [7]:
#Q_No_76> Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()

# Modify an element in the copy
copy_arr[0] = 99 

# Print the original array and the modified copy
print("Original array (arr1):", arr1)
print("Modified copy (copy_arr):", copy_arr)

In [8]:
#Q_No_77>Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
matrix = np.random.randint(0, 10, (3, 3))
view_slice = matrix[1:, 1:] 
view_slice[0, 0] = 99 
print("Original matrix after modification:\n", matrix)
print("Extracted slice (view_slice):\n", view_slice)

In [16]:
#Q_No_78> Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:3, :]  # Extracting rows 1 and 2, all columns
view_b += 5

# Print the original array and the modified slice
print("Original array_a after modification:\n", array_a)
print("Extracted slice (view_b) after addition:\n", view_b)

In [10]:
#Q_No_79>Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in the reshaped view
reshaped_view[0, 0] = 99  # Changing the first element of the reshaped view


# Print the original array and the modified reshaped view
print("Original array (orig_array) after modification:\n", orig_array)
print("Reshaped view (reshaped_view):\n", reshaped_view)

In [11]:
#Q_No_80> Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data
data = np.random.randint(0, 10, (3, 4))
data_copy = data[data > 5].copy()
if data_copy.size > 0:  # Check if there are elements greater than 5
    data_copy[0] = 99

print("Original array (data):\n", data)
print("Modified copy (data_copy):\n", data_copy)    

In [12]:
#Q_No_81> Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
arr1=np.random.randint(1,10,size=(3,4))
arr2=np.random.randint(1,10,size=(3,4))
print(arr1+arr2)
print(arr1-arr2)

In [13]:
#Q_No_82>Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
arr1=np.random.randint(1,10,size=(3,2))
arr2=np.random.randint(1,10,size=(2,4))
print(np.dot(arr1,arr2))

In [14]:
#Q_No_83>Create a matrix `E` and find its transpose.
E=np.random.randint(1,10,size=(3,3))
print("Original array",E)
print("Transpose Array",E.T)

In [15]:
#Q_No_84>Generate a square matrix `F` and compute its determinant.
F=np.random.randint(1,10,size=(3,3))
np.linalg.det(F)

In [ ]:
#Q_No_85>Create a square matrix `G` and find its inverse.
G=np.random.randint(1,10,size=(3,3))
print("Original array",G)
print("Transpose Array",np.linalg.inv(G))